### PR TITLE
Add `googletest` for more expressive matchers

### PR DESCRIPTION
**Pull request by mgeisler**
This is a pilot of the new https://docs.rs/googletest testing library.

### CODE REVIEW

**Comment by mgeisler** [comment]
> Sorry @hovinen... we need the code to work with Rust 1.59 since that's what we use in Android.

Let me run CI again with https://github.com/google/googletest-rust/commit/a6a69b1fc2780bda325fa542c37ceb96925e7bcf.

**Comment by mgeisler** [comment]
Interesting, using https://github.com/google/googletest-rust/commit/a6a69b1fc2780bda325fa542c37ceb96925e7bcf breaks in new ways:

```
error[E0597]: `file` does not live long enough
    --> src/backends/rust.rs:990:38
     |
990  |           let scope = lint::Scope::new(&file);
     |                                        ^^^^^ borrowed value does not live long enough
991  |           let find_fields = |id| {
992  | /             find_constrained_parent_fields(&scope, id)
993  | |                 .map(|field| field.id().unwrap())
994  | |                 .collect::<Vec<_>>()
     | |____________________________________- returning this value requires that `file` is borrowed for `'static`
...
1002 |       }
     |       - `file` dropped here while still borrowed
```

**Comment by mgeisler** [comment]
> This looks like it could be related to the problems we discovered with using references inside various matchers. Could you try against the branch google/googletest-rust@test_532117755?

Yep, that fixes it! Thanks :smile:

**Comment by mgeisler** [comment]
> I plan to push 0.7.0 this week if there are no major problems.

Cool, we'll look at it again then! I believe we'll need to get googletest added to AOSP before we can merge anything, but we can talk about it then.

**Review by DeltaEvo — APPROVED** [review]
